service: ziplink

app: ziplink

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: eu-west-2
  stage: ${opt:stage,'staging'}

  tags:
    APP: 'ziplink'
    ENV: ${sls:stage}

  stackTags:
    APP: 'ziplink'
  deploymentBucket:
    name: ziplink-serverless
    maxPreviousDeploymentArtifacts: ${self:custom.previous_deployments.${sls:stage}}
    blockPublicAccess: true

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action:
            - 'apigatewway:*'
            - 'dynamodb:PutItem'
            - 'dynamodb:GetItem'

  httpApi:
    disableDefaultEndpoint: true

plugins:
  - serverless-plugin-resource-tagging
  - serverless-python-requirements

package:
  individually: true

custom:
  stages:
    - local
    - staging
    - production
  pythonRequirements:
    layer: true
    slim: true
  env:
    local: 'local'
    staging: 'staging'
    production: 'production'
  previous_deployments:
    local: 0
    staging: 1
    production: 5
  db:
    local: 'DYNAMO_DB'
    staging: 'DYNAMO_DB'
    production: 'DYNAMO_DB'

functions:
  redirect-url:
    handler: apps.short_links.handlers.redirect_handler
    events:
      - httpApi:
          path: /{param}
          method: get
          restApiId: !Ref HttpApi  # Reference the custom API Gateway
    package:
      patterns:
        - 'apps/redirect/**'
        - 'apps/common/**'
    environment:
      DB: ${self:custom.db.${sls:stage}}
    layers:
      - Ref: PythonRequirementsLambdaLayer

  create-redirect-url:
    handler: apps.short_links.handlers.create_handler
    events:
      - httpApi:
          path: /
          method: post
          restApiId: !Ref HttpApi  # Reference the custom API Gateway
    package:
      patterns:
        - 'apps/redirect/**'
        - 'apps/common/**'
    environment:
      DB: ${self:custom.db.${sls:stage}}
    layers:
      - Ref: PythonRequirementsLambdaLayer

resources:
  - ${file(infrastructure/aws/dynamodb_table.yml)}
  - ${file(infrastructure/aws/api_gateway.yml)}
