# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: url-redirect
# app and org for use with dashboard.serverless.com
app: ziplink
org: ziplink

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: eu-west-2
  stage: ${opt:stage,'staging'}

  tags:
    APP: 'ziplink'
    ENV: ${sls:stage}

  stackTags:
    APP: 'ziplink'
  deploymentBucket:
    name: ziplink-app-serverless
    maxPreviousDeploymentArtifacts: ${self:custom.previous_deployments.${sls:stage}}
    blockPublicAccess: true

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action:
            - 'apigatewway:*'

plugins:
  - serverless-plugin-resource-tagging
  - serverless-python-requirements

package:
  individually: true

custom:
  stages:
    - local
    - staging
    - production
  pythonRequirements:
    layer: true
    slim: true
  env:
    local: "local"
    staging: "staging"
    production: "production"
  previous_deployments:
    local: 0
    staging: 1
    production: 5

functions:
  redirect-url:
    handler: apps.redirect.handlers.handler
    events:
      - httpApi:
          path: /{param}
          method: get
    package:
      # Directories and files to include in the deployed package
      patterns:
        - 'apps/redirect/**'
        - 'apps/common/**'
    layers:
      - Ref: PythonRequirementsLambdaLayer

resources:
  - ${file(infrastructure/dynamodb_table.yml)}
  - ${file(infrastructure/api_gateway.yml)}
