version: '3'

networks:
  ziplink_app_network:
    driver: bridge
services:
  db:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    restart: always
    networks:
      - 'ziplink_app_network'
