version: '3'

networks:
  ziplink_app_network:
    driver: bridge
services:
  db:
    image: 'amazon/dynamodb-local:latest'
    ports:
      - 8090:8000
    command: '-jar DynamoDBLocal.jar -inMemory -sharedDb'
    container_name: dynamodb-local
    restart: always
    volumes:
      - './docker/dynamodb:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal
    networks:
      - 'ziplink_app_network'

  db-init:
    depends_on:
      - db
    image: amazon/aws-cli
    environment:
      AWS_REGION: 'us-west-2'
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    networks:
      - 'ziplink_app_network'
    command: >-
      dynamodb create-table
          --table-name short_url
          --attribute-definitions
              AttributeName=hash,AttributeType=S
          --key-schema
              AttributeName=hash,KeyType=HASH
          --billing-mode PAY_PER_REQUEST
          --endpoint-url http://dynamodb-local:8000
