Resources:
  Type: AWS::DynamoDB::Table
  TableName: 'short_url'
  Properties:
    AttributeDefinitions:
      - AttributeName: hash
        AttributeType: S
    KeySchema:
      - AttributeName: hash
        KeyType: HASH
    BillingMode: 'PAY_PER_REQUEST'
    TimeToLiveSpecification:
      - AttributeName: expires_at
      - Enabled: true
